# This workflow handles formatting, testing, and SonarQube scanning for the PODPAC repository.
name: Python Workflow

on:
  push:
    branches: [main, develop]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  formatting:
    name: Formatting
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: pip install --upgrade pip setuptools && pip install .[devall]

      - name: Run Black Format Checks
        run: black --version; black --check --diff -l 120 . > black-report.txt

      - name: Artifact Black Report
        uses: actions/upload-artifact@v4
        with:
          name: black-report
          path: black-report.txt
          retention-days: 1

      - name: Run flake8 Format Checks
        run: flake8 --version; flake8 --format=pylint --ignore=E,W,D,I,N806,N815,N818,Q000,Q001,Q002,S001,A001,A002,A003,A005,B008,B028 --tee --output-file=flake8-report.txt .

      - name: Artifact flake8 Report
        uses: actions/upload-artifact@v4
        with:
          name: flake8-report
          path: flake8-report.txt
          retention-days: 1


  unit-testing:
    name: Unit Testing
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          pip install --upgrade pip setuptools && pip install .[devall]

      - name: Run Pytest with Coverage
        run: |
          coverage run --branch \
          -m pytest -m "not integration" --continue-on-collection-errors || \
          { echo "WARNING: Some tests have failed. (Temporarily ignored)"; true; }
          coverage xml -o coverage.xml
          sed -i 's,<source>.*/podpac</source>,<source>podpac</source>,' coverage.xml
      - name: Artifact Coverage Document
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage.xml
          retention-days: 1

  document-testing:
    name: Document Testing
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          path: podpac

      - name: Checkout Examples Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: "creare-com/podpac-examples"
          path: podpac-examples

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          pip install --upgrade pip setuptools && cd podpac && pip install .[devall]

      - name: Run doc tests
        run: |
          cd podpac/doc && ./test-docs.sh && cd ../.. || \
          { echo "WARNING: Some document tests have failed. (Temporarily ignored)"; true; }

      - name: Artifact Doctest Document
        uses: actions/upload-artifact@v4
        with:
          name: doctest
          path: podpac/build/output.txt
          retention-days: 1

  sonarqube_scan:
    name: SonarQube Scan
    needs: [unit-testing]
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Download Coverage Artifact
        uses: actions/download-artifact@v4
        with:
          name: coverage
          path: .

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@fd88b7d7ccbaefd23d8f36f73b59db7a3d246602
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
